name: PDF

on:
  workflow_dispatch:
  workflow_run:
    branches: [master]
    workflows: [Deploy]
    types: completed

permissions:
  contents: write

jobs:
  Build:
    name: Build
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "*"
          check-latest: true
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml

      - name: Install node_modules
        run: |
          pnpm install --frozen-lockfile
          pnpm puppeteer browsers install chrome

      - name: Build PDF
        run: |
          pnpm pdf

      - name: Release
        run: |
          gh release delete surge-xt-manual -y
          gh release create surge-xt-manual dist/Surge-XT-Manual.pdf -t "Surge XT Manual" -n "PDF version of the Surge XT Manual"
