name: Surge XT Manual PDF

on:
  push:
    paths:
      - 'manual_xt/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 5

      - name: Build PDF
        run: >
          wget -q https://github.com/jgm/pandoc/releases/download/3.1.1/pandoc-3.1.1-1-amd64.deb;
          sudo apt install ./pandoc-3.1.1-1-amd64.deb;
          wget -q https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.bullseye_amd64.deb;
          sudo apt install ./wkhtmltox_0.12.6.1-2.bullseye_amd64.deb;
          cd manual_xt;
          pandoc -f gfm -t html Surge-XT.md -o Surge-XT-Manual.pdf
          --css ./pdf.css -V title:""
          --pdf-engine-opt="--footer-font-name" --pdf-engine-opt="Lato"
          --pdf-engine-opt="--footer-font-size" --pdf-engine-opt="12"
          --pdf-engine-opt="--footer-center" --pdf-engine-opt="[page]"
          --pdf-engine-opt="--no-footer-line" --pdf-engine-opt="--footer-spacing" --pdf-engine-opt="10"
          --pdf-engine-opt="--disable-smart-shrinking"
          --pdf-engine-opt="--zoom" --pdf-engine-opt="1"

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release edit surge-xt-manual -n "PDF of the [Surge XT Manual](https://surge-synthesizer.github.io/manual-xt/)"
          gh release upload surge-xt-manual ./manual_xt/Surge-XT-Manual.pdf --clobber
